# Generated by Django 6.0.2 on 2026-02-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='formation_interessee',
            field=models.CharField(choices=[('niveau1', 'Niveau 1 : Les Assistants IA'), ('niveau2', "Niveau 2 : L'Automatisation"), ('les_deux', 'Les deux niveaux')], default='niveau1', max_length=20, verbose_name='Formation intéressée'),
        ),
    ]
